workflow:
  rules:
    # Merge Request: consentite
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    
    # Branch ufficiali: consentiti
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "dev"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "preprod"'
      when: always
    - if: '$CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "prod"'
      when: always
    
    # BLOCCA TUTTO IL RESTO
    - when: never


include:
  - local: "ci/pipeline-dev.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH == "dev" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "dev"'

  - local: "ci/pipeline-preprod.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH == "preprod" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "preprod"'

  - local: "ci/pipeline-prod.yml"
    rules:
      - if: '$CI_COMMIT_BRANCH == "prod" || $CI_MERGE_REQUEST_TARGET_BRANCH_NAME == "prod"'

  - local: "ci/pipeline-empty.yml"
    rules:
      - when: always