spring.application.name=micdl-etl
spring.jmx.enabled=false
spring.profiles.active=dev

# ========================================
# Riduzione log auto-configuration
# ========================================
logging.level.org.springframework.boot.autoconfigure=INFO
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.springframework=INFO
logging.level.org.hibernate=ERROR

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=none

# Ottimizzazioni Hibernate (opzionali ma utili)
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.order_updates=true

# =========================================================
# Modifica della massima grandezza per un file ricevuto
# =========================================================
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
