spring.application.name=micdl-etl
spring.jmx.enabled=false

# =========================
# Riduzione log auto-configuration
# =========================
logging.level.org.springframework.boot.autoconfigure=INFO

# dimensione massima del batch verso database
micdl.batch.size=1000